testing on shep

diff --git a/.github/workflows/test-check.yml b/.github/workflows/test-check.yml
--- a/.github/workflows/test-check.yml
+++ b/.github/workflows/test-check.yml
@@ -11,9 +11,19 @@ jobs:
         uses: actions/checkout@v4
         with:
           submodules: recursive
+<<<<<<< HEAD
           token: ${{ secrets.PAT_TOKEN }}
       - name: Run UNITY Testing files
         run: |
           docker compose run --rm ner-gcc-arm \
             sh -e -c "python3 Drivers/Embedded-Base/ner_environment/build_system/test_runner.py"
             
+=======
+      - name: Run UNITY Testing files
+        run: |
+          if ! docker compose run --rm ner-gcc-arm \
+            bash -c "python3 Drivers/Embedded-Base/ner_environment/build_system/test_runner.py"; then
+            echo "Unit tests failed."
+            exit 1
+          fi
+>>>>>>> ff09ec3 (testing on shep)
